# Introduction to Julia

Contents:

- [Introduction to Julia](#Introduction-to-Julia)  
  - [Work Environment](#Work-Environment)  
  - [Jupyter Basics](#Jupyter-Basics)  
  - [Julia Basics](#Julia-Basics)   


In this lab we will: 

(1) Load the lab GitHub repository locally;

(2) Set up our work environment by installing Julia and Jupyter; 

(3) Cover Jupyter basics; 

(4) Go over some Julia basics.

The goal is to set up a stable work environment for the rest of the quarter while getting a taste of the Julia language.

Today's material borrows quite a lot from [Quantitative Economics with Julia by QuantEcon](https://julia.quantecon.org/), so I encourage everyone to check it out for more details.

---
## Work Environment

To set up the necessary work environment for these labs, we need to do the following three things:

- Download and install Julia;
- Download and install Jupyter;
- "Connect" Jupyter with Julia.

We will first need to download and install the current stable version of Julia by visiting [this page](https://julialang.org/downloads/) and following the instructions for the appropriate operating system. 

Then we will need to visit [this page](https://www.anaconda.com/products/individual) to download and install Anaconda, which essentially a package management tool that includes Jupyter. To learn more about Anaconda, read the [Wikipedia page](https://en.wikipedia.org/wiki/Anaconda_(Python_distribution)). 

Once both Julia and Anaconda are installed, we can perform the final step of linking Jupyter with Julia. Open Julia -- we should see the following window pop up:

![](images/repl.png)

This is the Julia REPL (Read-Evaluate-Print Loop). 

Now type `]` to enter package mode, then type `add IJulia`.

![](images/repl_package_mode.png)

We then click `Enter` on the keyboard to run the command. This will install the IJulia kernel, which should automatically link Julia with Jupyter. After the installation is complete, we click `Backspace` on the keyboard to leave package mode.

We can now type `using IJulia; notebook()` into the REPL to launch Jupyter Notebook. If this running this command leads to an error or the prompt `install Jupyter via Conda, y/n? [y]:`, then we can alternatively launch Jupyter Notebook by finding where it lives on our machine and/or typing `jupyter notebook` into the Anaconda Prompt. In any case, we should see something similar to the following tab open in our web browser (but in a different directory):

![](images/jupyter_repository.png)

We can now manually navigate to our preferred directory (folder) and create new notebooks, along with other types of documents. When we open a document, it will open as a new tab in our web browser.

At this point we are all set-up and ready to code!

---
## Jupyter Basics

The keyboard shortcuts window says it best: "The Jupyter Notebook has two different keyboard input modes. Edit mode allows you to type code or text into a cell and is indicated by a green cell border. Command mode binds the keyboard to notebook level commands and is indicated by a grey cell border with a blue left margin."

At any given point in time in the Jupyter interface we are either in edit mode or command mode. We can tell which mode we are in using two indicators: (1) the color of the outline around a selected cell, and (2) the presence/absence of a pencil symbol next to the active kernel name at the upper-right corner of the notebook.

If we are in edit mode, then we should see the following:

![](images/jupyter_edit_mode.png)

Otherwise we should see the following:

![](images/jupyter_cmd_mode.png)

The following is a list of some very useful shortcuts:

- `Esc` triggers command mode if currently in edit mode;
- `Enter` triggers edit mode if currently in command mode;
- `Ctrl-Enter` runs selected cell;
- `Shift-Enter` runs selected cell and selects the next cell below;
- `Alt-Enter` runs selected cell and creates a new cell below;
- `D, D` deletes selected cell.

Check out more shortcuts by going into command mode and clicking the `H` key.

There are three types of cells (1) code, (2) Markdown, and (3) raw. We will mostly be interested in code and Markdown cells, so we disregard the final category. We can tell what type of cell we are dealing with by either (1) looking up at our toolbar 

![](images/jupyter_toolbar.png)

or by (2) looking to the left of the cell to check whether there is a `In [ ]:` present -- if so, then we have ourselves a code cell, otherwise it is a Markdown cell.

A couple more useful shortcuts:

- `M` changes a selected cell type to Markdown if in command mode;
- `Y` changes a selected cell type to code if in command mode.

Jupyter is simple and intuitive enough that the above should be enough to get us going.

---
## Julia Basics

### Packages

Let us start by loading Julia packages.

In [1]:
using LinearAlgebra # Load LinearAlgebra package
using Statistics # Load Statistics package

Suppose we do not have the `LinearAlgebra` package available in our environment. 

In this case, loading LinearAlgebra with `using` will not work, since we first need to install the package using the following code: 

In [ ]:
using Pkg # Load `Pkg`, which can be used to install packages
Pkg.add("LinearAlgebra") # Install `LinearAlgebra` package
using LinearAlgebra

   Resolving package versions...


We could have alternatively opened the REPL, entered package mode by clicking `]`, and ran `add LinearAlgebra`.

![](images/repl_linearalgebra.png)


### Simple Data Types

Now that basic package management is out of the way, we can start talking about data types.

Suppose we have randomly-generated variables $x$ and $y$, and would like to check whether $x > y$. Let's call this condition A. We can store the status of condition A as a Boolean variable $z$. 

In [11]:
x = randn() # Generate random value `x`
y = randn() # Generate random value `y`
z = x > y   # Store status of condition A as variable `z`
message = "x = $(x) and y = $(y)," * "therefore condition A is $(z)."
message

"x = 0.16617983288747074 and y = -1.778412509974055,therefore condition A is true."

Notice that we used the `randn()` function to generate a random $x,y \in \mathbb{R}$. 
Furthermore, we generated a string called `message` by concatenating two separate strings using `*`.
We print the values of variable `x`, `y`, and `z` in `message` using `$`.  

Let's confirm that `message` is indeed a string:

In [12]:
typeof(message)

String

Let's also check the data type of `x` (and equivalently `y`):

In [5]:
typeof(x)

Float64

Now let's check the data type of `z`:

In [6]:
typeof(z)

Bool

So far we've seen strings, floats, and booleans, but we also have integers:

In [13]:
y = 5
typeof(y)

Int64

Since we have a float `x` and an integer `y`, let's test out some basic arithmetic operations with them:

In [16]:
@show x + y
@show x - y
@show x * y
@show x / y
@show x - (-y)
@show 3x - 4y
@show x^(-1);


x + y = 5.166179832887471
x - y = -4.833820167112529
x * y = 0.8308991644373537
x / y = 0.03323596657749415
x - -y = 5.166179832887471
3x - 4y = -19.501460501337586
x ^ -1 = 6.017577359565366


Notice that we used the `@show` macro the print out equations.
Furthermore, we ended the last line of the cell with a `;` to supress the redundant printing of the output of `x^(-1)`. 
See what happens when you construct a similar cell without `;` at the end.

But did you know we can also apply arithmetic operations to booleans?

In [18]:
z1 = true # define a true boolean 
z2 = false # define a false boolean

@show x
@show z1 + 0
@show z2 + 0
@show z1 + z2 
@show x + z1
@show x * z1
;

x = 0.16617983288747074
z1 + 0 = 1
z2 + 0 = 0
z1 + z2 = 1
x + z1 = 1.1661798328874706
x * z1 = 0.16617983288747074


Let's give `x` and `y` imaginary components, and play around with the resulting imaginary numbers.

In [14]:
@show x = x + 3im
@show y = y + 2im
@show x + y
@show x - y
@show x * y
@show x / y
@show x - (-y)
@show 3x - 4y
@show x^(-1);

x = x + 3im = 1.3963755552962687 + 3.0im
y = y + 2im = 5 + 2im
x + y = 6.3963755552962684 + 5.0im
x - y = -3.6036244447037316 + 1.0im
x * y = 0.9818777764813431 + 17.792751110592537im
x / y = 0.44765095780970154 + 0.4209396168761194im
x - -y = 6.3963755552962684 + 5.0im
3x - 4y = -15.810873334111193 + 1.0im
x ^ -1 = 0.12752445757519595 - 0.2739759882465268im


### Introduction to Arrays

We can also collect data into arrays.

In [25]:
a = [10; 20; 30]

@show ndims(a)
@show typeof(a)

ndims(a) = 1
typeof(a) = Vector{Int64}


Vector{Int64} (alias for Array{Int64, 1})

The output here tells us that `a` is a one-dimensional array containing `Int64` data. 

In [24]:
b = [1.0, 2.0, 3.0]
@show typeof(b)

typeof(b) = Vector{Float64}


Vector{Float64} (alias for Array{Float64, 1})

`b` seems to have the same dimensions as `a`, but it contains `Float64` data instead of integer data.

Suppose we try to include multiple data types in a single array:

In [26]:
c = [1, 1.0, true, "text"]

4-element Vector{Any}:
    1
    1.0
 true
     "text"

This is **undesirable**, but as we can see -- it works.

Let's check out the dimensions and size of array/vector `b`:

In [27]:
@show ndims(b) # Show dimensions of vector `b`
@show size(b); # Show size of vector `b`

ndims(b) = 1
size(b) = (3,)


The above output essentially tells us that `b` is a vector with 3 entries. 

I say that `b` is a vector since a one-dimensional array is equivalent to a vector, while a two-dimensional array is equivalent to a matrix. 

We confirm this in the following cell:

In [28]:
@show Array{Float64, 1} == Vector{Float64}
@show Array{Float64, 2} == Matrix{Float64};

Array{Float64, 1} == Vector{Float64} = true
Array{Float64, 2} == Matrix{Float64} = true


There are two different ways we can create a column vector:

In [29]:
col1 = [1, 2, 3]
col2 = [1; 2; 3]
col1 == col2 # Test if both are column vectors

true

We can also create row vectors in the following manner:

In [30]:
row1 = [1 2 3]

1×3 Matrix{Int64}:
 1  2  3

Let's check the dimensions and size of the row vector `row1`:

In [31]:
@show ndims(row1)
@show size(row1);

ndims(row1) = 2
size(row1) = (1, 3)


According to the above output, row vectors are 2-dimensional -- in other words, they are matrices.

Furthermore, unlike column vectors, row vectors are not flat. The above output shows that `row1` has one row and three columns.

Let's create a more traditional-looking matrix `A`:

In [32]:
A = [1 2; 3 4]


2×2 Matrix{Int64}:
 1  2
 3  4

Now let's transpose `A`:

In [33]:
A'

2×2 adjoint(::Matrix{Int64}) with eltype Int64:
 1  3
 2  4

We can access the second column of `A` in the following manner:

In [37]:
A[:,2]


2-element Vector{Int64}:
 2
 4

Analogously, we may access the second row of `A` in the following manner:

In [38]:
A[2,:]



2-element Vector{Int64}:
 3
 4

Notice that when we accessed the second row of `A`, the output was a flat array (column vector).

You may simply transpose it to obtain it in row vector form:

In [39]:
A[2,:]'

1×2 adjoint(::Vector{Int64}) with eltype Int64:
 3  4

What if we want to access the $(2,2)$ entry of `A`?

In [41]:
A[2,1]

3

Now let's talk briefly about array creation.

A nice way of creating zero vectors is using the `zeros()` function:

In [42]:
zeros(2)

2-element Vector{Float64}:
 0.0
 0.0

Similarly, we can use `zeros()` to create matrices:

In [43]:
zeros(2,2)

2×2 Matrix{Float64}:
 0.0  0.0
 0.0  0.0

More generally, we may use the `fill()` function to create arrays with customized uniform entries:

In [44]:
fill(1, 2, 4)

2×4 Matrix{Int64}:
 1  1  1  1
 1  1  1  1

How do we copy an array? Let's try simply using an equality:

In [45]:
x = fill(1, 3) # create vector `x`
y=x
y[2]=0
@show y
@show x;

y = [1, 0, 1]
x = [1, 0, 1]


What we did in the above cell is create a vector `x`, bind a new variable `y` to `x`, and then change the second entry of `y`. 

**We would expect this to alter `y` and not `x`, but it turns out this is not the case!**

So *we can't quite "copy" arrays using a simple equality. Instead we may use the `copy()` function*:

In [46]:
x = fill(1, 3)
y = copy(x) 
y[2] = 0
@show x
@show y;

x = [1, 1, 1]
y = [1, 0, 1]


**Notice that `x` didn't change, as desired.**

What if we don't want to copy an array exactly, but instead create an array of the same data type and size?

For this we can use the `similar()` function:

In [49]:
x = fill(1, 3)
y = similar(x)
@show x
@show y;


x = [1, 1, 1]
y = [2982237352976, 2982237352800, 2982237352992]


We may also use `similar()` to change the size while keeping the same data type:

In [50]:
x = fill(1, 3)
y = similar(x, 4)
@show x
@show typeof(x)
@show ndims(x)
@show size(x)
@show y
@show typeof(y)
@show ndims(y)
@show size(y); 

x = [1, 1, 1]
typeof(x) = Vector{Int64}
ndims(x) = 1
size(x) = (3,)
y = [2981322875024, 2981322875024, 0, 0]
typeof(y) = Vector{Int64}
ndims(y) = 1
size(y) = (4,)


We may also create a matrix similar to a vector:

In [51]:
x = fill(1, 3)
y = similar(x, 2, 2)
@show x
@show typeof(x)
@show ndims(x)
@show size(x)
@show length(x)
@show y
@show typeof(y)
@show ndims(y)
@show size(y)
@show length(y); 

x = [1, 1, 1]
typeof(x) = Vector{Int64}
ndims(x) = 1
size(x) = (3,)
length(x) = 3
y = [0 0; 0 0]
typeof(y) = Matrix{Int64}
ndims(y) = 2
size(y) = (2, 2)
length(y) = 4


### Array Operations

Let's create a random vector and then check out some of its properties:

In [52]:
v = [-1, 0, 1] # create vector `v` 

@show length(v)
@show sum(v)
@show mean(v)
@show std(v)
@show var(v)
@show maximum(v)
@show minimum(v)
@show extrema(v);

length(v) = 3
sum(v) = 0
mean(v) = 0.0
std(v) = 1.0
var(v) = 1.0
maximum(v) = 1
minimum(v) = -1
extrema(v) = (-1, 1)


We can sort the values in vector `v`:

In [53]:
w = sort(v, rev = true)
@show v
@show w;

v = [-1, 0, 1]
w = [1, 0, -1]


The way in which we sorted vector `v` above does not modify `v` itself. 

We can, however, also modify the original vector using the `sort()` function:

In [83]:
w = sort!(v, rev = true) 

@show v
@show w
@show v == w;

v = [1, 0, -1]
w = [1, 0, -1]
v == w = true


Notice that in the above cell we tested whether vectors `w` and `v` have the same values, and found that they do! This means that the original vector `v` was successfully modified.

How to do matrix multiplication?

In [54]:
A = [1 2; 2 1]
B = ones(2,2)
c = [1, 3]

@show A*B
@show A*B'
@show A*c 
@show c'*A;

A * B = [3.0 3.0; 3.0 3.0]
A * B' = [3.0 3.0; 3.0 3.0]
A * c = [7, 5]
c' * A = [7 5]


Let's solve $A \, x = c$:

In [55]:
x1 = A \ c # the best approach
x2 = inv(A) * c # alternative
x1 ≈ x2 # Here we are using \approx latex syntax + shift + Tab (in Windows, or just tab in Mac) to write the approximate symbol. 
# You can freely use latex to write greek letters and other alchemical/magical/mystical symbols if you feel like it

true

In the above cell I show two equivalent ways of solving for $x$.

I check their equivalence by testing whether `x1` is approximately equal to `x2` using the $\approx$ operator.

You may write $\approx$ in a code cell by typing "\approx" ($\LaTeX$ syntax) and hitting 'Tab' on your keyboard. 

In fact, you can write many other characters this way:

In [56]:
α = 1 # \alpha + Tab
β = 2 # \beta + Tab
γ = α + β # \gamma + Tab
γ


3

## * THIS IS REALLY IMPORTANT *

We can also easily do elementwise operations. 

For example, suppose we would like add 1 to every element of a vector or a matrix.

To do so, we **broadcast** the addition (`+`) operator by also including a period (`.+`):

In [57]:
A = ones(2,2)
x = ones(2) 
@show A .+ 1
@show x .+ 1;

A .+ 1 = [2.0 2.0; 2.0 2.0]
x .+ 1 = [2.0, 2.0]


Similarly, we can squared every entry of a vector/matrix:

In [58]:
@show (A .+ 1).^2
@show (x .+ 1).^2

(A .+ 1) .^ 2 = [4.0 4.0; 4.0 4.0]
(x .+ 1) .^ 2 = [4.0, 4.0]


2-element Vector{Float64}:
 4.0
 4.0

In fact, we can broadcast pretty much any function. Here's another example:

In [59]:
@show log.(A .+ 1)
@show log.(x .+ 1)

log.(A .+ 1) = [0.6931471805599453 0.6931471805599453; 0.6931471805599453 0.6931471805599453]
log.(x .+ 1) = [0.6931471805599453, 0.6931471805599453]


2-element Vector{Float64}:
 0.6931471805599453
 0.6931471805599453

Broadcasting is a very handy tool that you should end up using a lot to write efficient code.

Lastly, some basic linear algebra tools:

In [60]:
A = [1 2; 2 1]

2×2 Matrix{Int64}:
 1  2
 2  1

In [61]:
det(A)

-3.0

In [62]:
tr(A)

2

In [63]:
eigvals(A)

2-element Vector{Float64}:
 -1.0
  3.0

In [64]:
rank(A)

2

### Tuples

Tuples are essentially **immutable** data containers.

Let's create one:

In [65]:
tup = ("macro", 3.0, 2025)

("macro", 3.0, 2025)

Now let's try to change the second entry of `tup` to `1.0` (something that we often do with arrays):

In [66]:
tup[2] = 2.0

MethodError: MethodError: no method matching setindex!(::Tuple{String, Float64, Int64}, ::Float64, ::Int64)
The function `setindex!` exists, but no method is defined for this combination of argument types.

We obtained an error precisely because of the **immutability** of tuples -- once we define a tuple, we cannot change its entry values.

Let's try to store tuple entries as distinct variables:

In [69]:
class, quarter, year = tup
"Year: $year, Quarter: $quarter, Class: $class"

"Year: 2021, Quarter: 3.0, Class: macro"

We may also create **named tuples** and merge them:

In [67]:
tup3 = (q1 = "Fall", )
tup4 = (q2 = "Winter", q3 = "Spring")
tup5 = merge(tup3, tup4)

(q1 = "Fall", q2 = "Winter", q3 = "Spring")

Notice that to define a tuple with only one entry, we still need to include a comma with nothing to its right in the declaration.