# Introduction to Julia

Welcome to the computational bootcamp!

Over the next two weeks, you will learn the basics of the Julia programming language with examples in economic modelling. You will also learn about some of the modern programming infrastructure used in the profession.

The ideas and concepts we learn here are applicable across many languages and programming workflows; some of you may choose to use R or Python in the future.

Today, we will first work on getting up and running with Julia, and cover some basics. This material borrows quite a lot from [Quantitative Economics with Julia by QuantEcon](https://julia.quantecon.org/) and the [Julia documentation](https://docs.julialang.org/en/v1/) so I encourage everyone to check those resources out for more details.

# Setting up a Work Environment

Tools matter! In addition to a programming language itself, *coding* in that language requires an environment in which you can:
- create, edit, and execute programs
- keep track of changes to programs
- share your programs with collaborators

We're going to start with the first of these, and add more tools later.

## Installing Jupyter

[Jupyter](https://jupyter.org/) is an "interactive computing" environment that is compatible with multiple languages. The core concept of Jupyter is a "notebook" which combines formatted text, code, and output into a single file.

This document is a Jupyter notebook!

We will install Jupyter through the [Anaconda](https://www.anaconda.com/) computing package which additionally includes Python and other data science tools. Many, many data science tutorials around the internet start with the assumption of an Anaconda environment, so this will have positive spillover effects for you.

To install Anaconda, go here and follow the instructions: https://www.anaconda.com/download/

One note: if given the option, let Anaconda add Python to your PATH environment variable.

## Installing Julia

Now you can install Julia itself.

1. Download and install Julia following the [Juliaup instructions](https://github.com/JuliaLang/juliaup#installation)  
  - Windows: easiest method is `winget install julia -s msstore` in a Windows terminal  
  - Linux/Mac: in a terminal use `curl -fsSL https://install.julialang.org | sh`  
  - If you have previously installed Julia manually, you will need to uninstall previous versions before switching to `juliaup`.  
  - Alternatively, can manually install from [download page](http://julialang.org/downloads/), accepting all default options
2. Open Julia, by either  
  - Navigating to Julia through your menus or desktop icons (Windows, Mac), or  
  - Opening a terminal and type `julia` (which should work for all OS if you used `juliaup`.  Otherwise see [here](https://julialang.org/downloads/platform/))  
  You should now be looking at something like this  
  ![https://julia.quantecon.org/_static/figures/julia_term_1.png](https://julia.quantecon.org/_static/figures/julia_term_1.png)
  This is called the JULIA *REPL* (Read-Evaluate-Print-Loop), which we will discuss more later.
3. In the Julia REPL, hit `]` to enter package mode and then enter:  

In [ ]:
add IJulia

This adds packages for the `IJulia` kernel which links Julia to Jupyter you previously installed with Anaconda (i.e., allows your browser to run Julia code, manage Julia packages, etc.).

4. Exit the Julia REPL by hitting backspace to exit the package mode. Then type

In [ ]:
using IJulia; notebook()

This should create a new tab in our web browser, where we can manually navigate to our preferred directory (folder) and create new notebooks, along with other types of documents. When we open a document, it will open as a new tab in our web browser.

# Jupyter Basics

The keyboard shortcuts window says it best: "The Jupyter Notebook has two different keyboard input modes. Edit mode allows you to type code or text into a cell and is indicated by a green cell border. Command mode binds the keyboard to notebook level commands and is indicated by a grey cell border with a blue left margin."

At any given point in time in the Jupyter interface we are either in edit mode or command mode. We can tell which mode we are in using two indicators: (1) the color of the outline around a selected cell, and (2) the presence/absence of a pencil symbol next to the active kernel name at the upper-right corner of the notebook.

The following is a list of some very useful shortcuts:

- `Esc` triggers command mode if currently in edit mode;
- `Enter` triggers edit mode if currently in command mode;
- `Ctrl-Enter` runs selected cell;
- `Shift-Enter` runs selected cell and selects the next cell below;
- `Alt-Enter` runs selected cell and creates a new cell below;
- `D, D` deletes selected cell.

Check out more shortcuts by going into command mode and clicking the `H` key.

There are three types of cells:
- Markdown (text formatted to look nice, like this)
- code (text formatted per the conventions of a specific programming language)
- raw (unformatted text)

We will mostly be interested in code and Markdown cells, so we disregard the final category. We can tell what type of cell we are dealing with by either (1) looking up at our toolbar or by (2) looking to the left of the cell to check whether there is a `In [ ]:` present -- if so, then we have ourselves a code cell, otherwise it is a Markdown cell.

A couple more useful shortcuts:

- `M` changes a selected cell type to Markdown if in command mode;
- `Y` changes a selected cell type to code if in command mode.

Jupyter is simple and intuitive enough that the above should be enough to get us going.

# Julia Basics

## Packages

While Julia has quite a lot of functionality built in, very frequently we will want to use functionality which was developed by other programmers in the form of *packages*. In Julia, it is very easy to load packages with the `using` command. Here are a couple of packages that show up commonly in economics applications:

In [2]:
using LinearAlgebra
using Statistics

If you try to execute this cell for the first time, you may get an error message because the `LinearAlgebra` package is not part of your Julia "environment." We need to install it. There are two ways to do so. If we were in the REPL, we could enter package mode by pressing `]` and then typing `add LinearAlgebra'. Since we are not in the REPL, this is not available to us. Thankfully, Julia lets us do so entirely in code (which can be embedded in a Jupyter notebook like this):

In [ ]:
using Pkg   # load the `Pkg` package, which is Julia's built-in package-management package.
Pkg.add("LinearAlgebra") # Use the `Pkg` interface to install the `LinearAlgebra` package
Pkg.add("Statistics") # Do the same with the `Statistics` package
using LinearAlgebra

    Updating registry at `C:\Users\keato\.julia\registries\General.toml`
   Resolving package versions...
    Updating `C:\Users\keato\.julia\environments\v1.11\Project.toml`
  [37e2e46d] + LinearAlgebra v1.11.0
  No Changes to `C:\Users\keato\.julia\environments\v1.11\Manifest.toml`


You may have already noted that we can add *comments* to our code with the `#` character; when Julia is processing your code and it reaches a `#`, it ignores it and everything that follows until the end of the line.

## Variables

A variable, in Julia, is a name associated (or bound) to a value. It's useful when you want to store a value (that you obtained after some math, for example) for later use. For example:

In [19]:
# assign the value 10 to the variable x
x = 10

10

If you run this cell in a Jupyter notebook, it will output `10`.

In Julia, variables can take many different types, and those types could change. We can use the `typeof` function to ask Julia what type a particular variable is.

In [20]:
typeof(x)

Int64

In this case, `x` has type `Int64` which means it is a 64-bit integer (i.e. there are 64 ones and zeros that are used to store the value of `x`).

Let's see how the type of `x` changes when we reassign it.

In [21]:
x = 3.14

typeof(x)

Float64

`Float64` means 64-bit floating-point number. Floating point numbers are considerably more complicated than integers. We'll talk about that more later.

In [22]:
x = "Hello, World!"

typeof(x)

String

A `String` is a series of characters of any length. Strings can contain Unicode characters:

In [23]:
x = "人人生而自由，在尊严和权利上一律平等。"

"人人生而自由，在尊严和权利上一律平等。"

In fact, variable names can contain unicode characters as well!

In [24]:
δ = 0.00001

1.0e-5

In the Julia REPL and several other Julia editing environments, you can type many Unicode math
symbols by typing the backslashed LaTeX symbol name followed by tab. For example, the variable
name `δ` can be entered by typing `\delta`-*tab*, or even `α̂⁽²⁾` by `\alpha`-*tab*-`\^(2)`-*tab*.

# `println` and Strings

A very powerful tool in Julia is what I will call in-line string interpolation. When defining a `String`, the character `$` will expand a variable into its value within the string. Let's illustrate this with an example.

Suppose we have randomly-generated variables $x$ and $y$, and would like to check whether $x > y$. Let's call this condition A. We can store the status of condition A as a Boolean variable $A$. We can then print out a message telling us about the status of condition A.

In [25]:
x = randn() # Generate random value `x`
y = randn() # Generate random value `y`
A = x > y   # Store status of condition A as variable `A`
message = "x = $x and y = $y," * "therefore condition A is $A."
println(message)

x = 0.9782210509690409 and y = -0.7319204549617373,therefore condition A is true.


In this case, we assigned our message to the variable `message` and then used the `println` function to output the contents of `message`. But we could have used `println` directly:

In [26]:
println("The current value of x is $x.")

The current value of x is 0.9782210509690409.


You can even do math inside of `String` defintions, though you must enclose it in parentheses:

In [27]:
println("Adding 1 to x gives $(x+1).")

Adding 1 to x gives 1.978221050969041.


## Arithmetic

Julia supports all of the basic arthimetic operations with standard syntax:

In [28]:
@show x + y
@show x - y
@show x * y
@show x / y
@show x - (-y)
@show 3x - 4y
@show x^(-1);

x + y = 0.24630059600730358
x - y = 1.7101415059307783
x * y = -0.7159799966784092
x / y = -1.3365127922544253
x - -y = 0.24630059600730358
3x - 4y = 5.862344972754071
x ^ -1 = 1.0222638318909458


What's this `@show` thing? Julia supports *macros*, which are essentially shorthand ways to accomplish more complicated operations. The `@show` macro prints out the result of an expression along with the expression itself.

Note also that we ended the last line of the cell with a `;` to supress the redundant printing of the output of `x^(-1)`. 
See what happens when you construct a similar cell without `;` at the end.

Arithmetic isn't just for floats and integers. What happens if we apply arithmetic operations to booleans?

In [29]:
z1 = true # define a true boolean 
z2 = false # define a false boolean

@show x
@show z1 + 0
@show z2 + 0
@show z1 + z2 
@show x + z1
@show x * z1
;

x = 0.9782210509690409
z1 + 0 = 1
z2 + 0 = 0
z1 + z2 = 1
x + z1 = 1.978221050969041
x * z1 = 0.9782210509690409


Imaginary components work just the same way!

In [30]:
x = 5.5 + 3.25im
y = 0.2 + 0.6im

@show x + y
@show x - y
@show x * y
@show x / y
@show x - (-y)
@show 3x - 4y
@show x^(-1);

x + y = 5.7 + 3.85im
x - y = 5.3 + 2.65im
x * y = -0.8499999999999999 + 3.9499999999999997im
x / y = 7.625000000000001 - 6.624999999999999im
x - -y = 5.7 + 3.85im
3x - 4y = 15.7 + 7.35im
x ^ -1 = 0.13476263399693722 - 0.07963246554364471im


## Introduction to Arrays

We can also collect data into arrays.

In [31]:
a = [10; 20; 30]

@show ndims(a)
@show typeof(a)

ndims(a) = 1
typeof(a) = Vector{Int64}


Vector{Int64} (alias for Array{Int64, 1})

The output here tells us that `a` is a one-dimensional array containing `Int64` data. 

In [32]:
b = [1.0, 2.0, 3.0]
@show typeof(b)

typeof(b) = Vector{Float64}


Vector{Float64} (alias for Array{Float64, 1})

`b` has a similar type to `a`, but its contents are `Float64` instead of `Int64`.

If we want, we can include multiple types of data in a single array.

In [33]:
c = [1, 1.0, true, "text"]

4-element Vector{Any}:
    1
    1.0
 true
     "text"

This is **undesirable**, but as we can see -- it works.

Let's check out the dimensions and size of array/vector `b`:

In [34]:
@show ndims(b) # Show dimensions of vector `b`
@show size(b); # Show size of vector `b`

ndims(b) = 1
size(b) = (3,)


The above output essentially tells us that `b` is a vector with 3 entries. 

I say that `b` is a vector since a one-dimensional array is equivalent to a vector, while a two-dimensional array is equivalent to a matrix. 

We confirm this in the following cell:

In [35]:
@show Array{Float64, 1} == Vector{Float64}
@show Array{Float64, 2} == Matrix{Float64};

Array{Float64, 1} == Vector{Float64} = true
Array{Float64, 2} == Matrix{Float64} = true


There are two different ways we can create a column vector:

In [36]:
col1 = [1, 2, 3]
col2 = [1; 2; 3]
col1 == col2 # Test if both are column vectors

true

We can also create row vectors in the following manner:

In [37]:
row1 = [1 2 3]

1×3 Matrix{Int64}:
 1  2  3

Let's check the dimensions and size of the row vector `row1`:

In [38]:
@show ndims(row1)
@show size(row1);

ndims(row1) = 2
size(row1) = (1, 3)


According to the above output, row vectors are 2-dimensional -- in other words, they are matrices.

Furthermore, unlike column vectors, row vectors are not flat. The above output shows that `row1` has one row and three columns.

## Matrices

Let's create a more traditional-looking matrix `A`:

In [39]:
A = [1 2; 3 4]

2×2 Matrix{Int64}:
 1  2
 3  4

We can refer to specific elements of `A` using brackets:

In [43]:
@show A[1,1]
@show A[1,2]
@show A[2,1]
@show A[2,2];

A[1, 1] = 1
A[1, 2] = 2
A[2, 1] = 3
A[2, 2] = 4


We can transpose `A` with the character `'`:

In [44]:
A'

2×2 adjoint(::Matrix{Int64}) with eltype Int64:
 1  3
 2  4

A very powerful tool in Julia is the "slice" -- the ability to refer to specific submatrices within a larger matrix. Suppose we wanted to extract just the second column of `A`. We can do this by telling Julia we want all rows of `A` with the `:` character:

In [45]:
A[:,2]

2-element Vector{Int64}:
 2
 4

We could also ask Julia for the second row of `A`:

In [46]:
A[2,:]

2-element Vector{Int64}:
 3
 4

Notice that when we accessed the second row of `A`, the output was a flat array (column vector).

You may simply transpose it to obtain it in row vector form:

In [47]:
A[2,:]'

1×2 adjoint(::Vector{Int64}) with eltype Int64:
 3  4

## Creating and Copying Arrays

A nice way of creating a zero vector is using the `zeros()` function:

In [48]:
zeros(2)

2-element Vector{Float64}:
 0.0
 0.0

You can use `zeros()` to create matrices as well:

In [49]:
zeros(2,2)

2×2 Matrix{Float64}:
 0.0  0.0
 0.0  0.0

But what if we don't want our matrix to be filled with zeros? We can use the `fill()` function to create a matrix with anything we want:

In [50]:
fill(0.5, 2, 4)

2×4 Matrix{Float64}:
 0.5  0.5  0.5  0.5
 0.5  0.5  0.5  0.5

Often, we will want to copy arrays, for example if the array represents data that we want to manipulate. Let's see what happens if we use the assignment operator:

In [51]:
x = fill(1, 3)  # create vector `x`: [1, 1, 1]
y=x             # copy(?) x into the new vector y
y[2]=0          # set the second element of y equal to zero
@show y         # what does y look like now?
@show x;        # ... but what does x look like now?

y = [1, 0, 1]
x = [1, 0, 1]


What we did in the above cell is create a vector `x`, bind a new variable `y` to `x`, and then change the second entry of `y`. 

**We would expect this to alter `y` and not `x`, but it turns out this is not the case!**

So *we can't quite "copy" arrays using a simple equality. Instead we may use the `copy()` function*:

In [52]:
x = fill(1, 3)
y = copy(x) 
y[2] = 0
@show x
@show y;

x = [1, 1, 1]
y = [1, 0, 1]


**Notice that `x` didn't change, as desired.**

What if we don't want to copy an array exactly, but instead create an array of the same data type and size?

For this we can use the `similar()` function:

In [53]:
x = fill(1, 3)
y = similar(x)
@show x
@show y;


x = [1, 1, 1]
y = [2313589080816, 141733921282, 1]


We may also use `similar()` to change the size while keeping the same data type:

In [54]:
x = fill(1, 3)
y = similar(x, 4)
@show x
@show typeof(x)
@show ndims(x)
@show size(x)
@show y
@show typeof(y)
@show ndims(y)
@show size(y); 

x = [1, 1, 1]
typeof(x) = Vector{Int64}
ndims(x) = 1
size(x) = (3,)
y = [776, 0, 2313480924624, 1]
typeof(y) = Vector{Int64}
ndims(y) = 1
size(y) = (4,)


We may also create a matrix similar to a vector:

In [55]:
x = fill(1, 3)
y = similar(x, 2, 2)
@show x
@show typeof(x)
@show ndims(x)
@show size(x)
@show length(x)
@show y
@show typeof(y)
@show ndims(y)
@show size(y)
@show length(y); 

x = [1, 1, 1]
typeof(x) = Vector{Int64}
ndims(x) = 1
size(x) = (3,)
length(x) = 3
y = [1 2313618345584; 3 2313618345616]
typeof(y) = Matrix{Int64}
ndims(y) = 2
size(y) = (2, 2)
length(y) = 4


## Array and Matrix Operations

Let's create a random vector and check out some of its properties using Julia functions!

In [57]:
v = randn(5)

@show length(v)
@show sum(v)
@show mean(v)
@show std(v)
@show var(v)
@show maximum(v)
@show minimum(v)
@show extrema(v);

length(v) = 5
sum(v) = 1.4452012958559783
mean(v) = 0.2890402591711957
std(v) = 0.8341950172008715
var(v) = 0.6958813267227624
maximum(v) = 1.4056641962418164
minimum(v) = -0.478980501143865
extrema(v) = (-0.478980501143865, 1.4056641962418164)


The `sort()` function works as expected:

In [58]:
w = sort(v)
@show v
@show w;

v = [-0.25364250935958554, 0.9488776965539445, -0.17671758643633204, -0.478980501143865, 1.4056641962418164]
w = [-0.478980501143865, -0.25364250935958554, -0.17671758643633204, 0.9488776965539445, 1.4056641962418164]


If we wanted to sort `w` without assigning it to a new variable, we cna use the `!` form of the function:

In [59]:
sort!(w)
@show w;

w = [-0.478980501143865, -0.25364250935958554, -0.17671758643633204, 0.9488776965539445, 1.4056641962418164]


Many Julia functions have *mutating* forms which are indicated with the `!` character. By convention, Julia functions without a `!` do not change their arguments. Those with `!` do.

### Matrix Multiplication

Matrix multiplication works as expected:

In [60]:
A = [1 2; 2 1]
B = ones(2,2)
c = [1, 3]

@show A*B
@show A*B'
@show A*c 
@show c'*A;

A * B = [3.0 3.0; 3.0 3.0]
A * B' = [3.0 3.0; 3.0 3.0]
A * c = [7, 5]
c' * A = [7 5]


Let's solve $A \, x = c$:

In [61]:
x1 = A \ c # the best approach
x2 = inv(A) * c # alternative
x1 ≈ x2 # Here we are using \approx latex syntax + shift + Tab (in Windows, or just tab in Mac) to write the approximate symbol. 
# You can freely use latex to write greek letters and other alchemical/magical/mystical symbols if you feel like it

true

In the above cell I show two equivalent ways of solving for $x$.

I check their equivalence by testing whether `x1` is approximately equal to `x2` using the $\approx$ operator.

Again, you may write $\approx$ in a code cell by typing "\approx" ($\LaTeX$ syntax) and hitting 'Tab' on your keyboard. 

### Element-wise Operations

Suppose we would like to add 1 to *every element* of a vector or matrix.

To do so, we **broadcast** the addition (`+`) operator by also including a period (`.+`):

In [62]:
A = ones(2,2)
x = ones(2) 
@show A .+ 1
@show x .+ 1;

A .+ 1 = [2.0 2.0; 2.0 2.0]
x .+ 1 = [2.0, 2.0]


We can do this with most operations. For example, we could square every element:

In [63]:
@show (A .+ 1) .^ 2

(A .+ 1) .^ 2 = [4.0 4.0; 4.0 4.0]


2×2 Matrix{Float64}:
 4.0  4.0
 4.0  4.0

In fact, most basic functions have a broadcast form. Here's another example:

In [64]:
@show log.(x .+ 1)

log.(x .+ 1) = [0.6931471805599453, 0.6931471805599453]


2-element Vector{Float64}:
 0.6931471805599453
 0.6931471805599453

Broadcasting is very handy and will help you write efficient code.

Lastly, some basic linear algebra functionality:

In [65]:
A = [1 2; 2 1]

@show det(A)
@show tr(A)
@show eigvals(A)
@show rank(A)

det(A) = -3.0
tr(A) = 2
eigvals(A) = [-1.0, 3.0]
rank(A) = 2


2